/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  math: ['math/demo'],
  skill: [
    'skill/introduction',
    {
      label: '杂项',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/other',
        },
      ],
    },
  ],
}

module.exports = sidebars
